### ISSUE TITLE
Cannot assign to read only property 'length' of string ''

### ISSUE THREAD

**Issue by DiegoRBaquero** [isaacs/minipass#44]
Noticing this on Node.js 16 and 18 for WebTorrent CI jobs.

Happening here: https://github.com/isaacs/minipass/blob/main/index.js#L628

Not really sure what's happening 🤔 

Ref:
https://github.com/webtorrent/webtorrent/actions/runs/3345756477/jobs/5541693022

**Comment by DiegoRBaquero** [comment]
Latest 3: https://github.com/isaacs/minipass/blob/ed5cbc0feb644e1226dfb5c8dea9083441b1d55e/index.js#L628

**Comment by isaacs** [comment]
Oh!  This is a tap parser error, actually, not a minipass error.  (So not minipass's fault, but still _my_ fault.)  Something is calling `.destroy()` on the tap parser stream, which is using its overwritten `.buffer` field (which tap parser sets to a string, but Minipass pre-v4 expects to be an array).

Once tap-parser is updated to use Minipass v4 (where it uses `this[BUFFER]` instead of `this.buffer`), it should be fine.  Sorry this isn't a quick fix, but the fixes required are currently in progress, and involve some semver-major changes in both libs. Next version of tap won't have this problem, because minipass hides its buffer array and tap-parser doesn't clobber it.

**Comment by isaacs** [comment]
Part of the fix is that the next major of tap-parser doesn't extend Minipass, it just extends EventEmitter, since it's not a readable stream anyway, so there's no "passthrough" required.
